inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

# Keep diffs clean
# Layout/TrailingEmptyLines:
#   EnforcedStyle: final_blank_line

# No way to avoid large blocks in RSpec
Metrics/BlockLength:
  Exclude:
    - spec/**/*

# Allow the gem to have a non-snakecase name
Naming/FileName:
  Exclude:
    - 'lib/my-services.rb'

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SpecialGlobalVars: 
  Enabled: false

Layout/LineLength:
  Enabled: false